// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtatuogneyrkbdxeocak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0YXR1b2duZXlya2JkeGVvY2FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzODQ5NzUsImV4cCI6MjA2Njk2MDk3NX0.M4_PAh-wDQbHBbyfIb7J-g_GNWAYD3Xjo54sg5eD3eo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});